### ISSUE TITLE
NPE  with version 1.14.2

### ISSUE THREAD

**Issue by shaileshmota** [BatchLabs/android-sdk#5]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.batch.android.q.d()' on a null object reference
       at com.batch.android.messaging.b.b.onDismiss(b.java:101)
       at com.batch.android.messaging.b.g.onDismiss(g.java:177)
       at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:233)
       at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:202)
       at com.batch.android.messaging.b.g.dismiss(g.java:191)
       at com.batch.android.messaging.b.g.e(g.java:281)
       at com.batch.android.messaging.view.a.d.a(d.java:196)
       at com.batch.android.messaging.view.a.d.lambda$RA81_w1pKOlhLEtFCrxfEmX3PGM(d.java:5)
       at com.batch.android.messaging.view.a.-$$Lambda$d$RA81_w1pKOlhLEtFCrxfEmX3PGM.onClick(-.java:2)
       at android.view.View.performClick(View.java:6256)
       at android.view.View$PerformClick.run(View.java:24701)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:251)
       at android.app.ActivityThread.main(ActivityThread.java:6572)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by abarisain** [comment]
Hello,

Do you have some additional information about when this happens? What kind of message is displayed on screen when it crashes?

If you'd like, you can chat to us on our support tool, available on our dashboard. That way we can see what campaign triggered this, and help us fix the issue faster.

Thanks,

**Comment by abarisain** [comment]
Closing: the issue has been found and will be fixed in a patch release.

Thanks!

**Comment by abarisain** [comment]
1.14.4 is out and fixes this
