### ISSUE TITLE
NPE with version 1.14.2

### ISSUE THREAD

**Issue by shaileshmota** [BatchLabs/android-sdk#6]
This might be related to https://github.com/BatchLabs/android-sdk/issues/5
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.batch.android.q.a()' on a null object reference
       at com.batch.android.messaging.b.b.onCancel(b.java:108)
       at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1600)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Comment by abarisain** [comment]
Thanks for the report.

All methods from "com.batch.android.messaging.b.b" suffer from this issue, so this is the same as #5. It has been fixed and released in 1.14.4!
