### ISSUE TITLE
IllegalStateException: Fragment not associated with a fragment manager

### ISSUE THREAD

**Issue by shaileshmota** [BatchLabs/android-sdk#9]
Hello Batch Team,  
We have noticed a new crash recently with `1.15.1` : 

```
Fatal Exception: java.lang.IllegalStateException: Fragment d{5336dd6 (b5e8eb3b-2162-40e8-a779-923fc13f86e7)} not associated with a fragment manager.
       at androidx.fragment.app.Fragment.requireFragmentManager(Fragment.java:910)
       at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:245)
       at androidx.fragment.app.DialogFragment.dismissAllowingStateLoss(DialogFragment.java:212)
       at com.batch.android.messaging.b.d.dismissAllowingStateLoss(d.java:131)
       at com.batch.android.messaging.b.d.e(d.java:197)
       at com.batch.android.messaging.view.a.c.i(c.java:177)
       at com.batch.android.messaging.view.a.c.lambda$4Oavn_OFBzq9o9t-4xOYqFMszaM(c.java)
       at com.batch.android.messaging.view.a.-$$Lambda$c$C2t6BYYO-NGdVzjayFRpFqBZAGE.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by abarisain** [comment]
Hello,

Thanks for the report, we'll investigate it. Could you post your androidx version here, please?

Also, do you have another crash stack trace in the same report, or one that looks like it?

We use DialogFragments, and this crash most often happens when the underlying activity has been destroyed. 
This can happen in two cases:
 - You manually destroyed it, but the DialogFragment doesn't know about that. We'll check if this use case is well supported.
 - The activity crashed, and was destroyed by the system.

We'll definitely handle the error better.

**Comment by shaileshmota** [comment]
For the android X version ( activity ), we have `appcompat = '1.1.0'` 

> Also, do you have another crash stack trace in the same report, or one that looks like it?

So far we have 6 of these and they are all similar. Not more information about the trace.
But we more information about the context : 
- Activity X onCreate, triggers an inapp campaign. 
- User moves from Activity X -> Y 
(Activity X is a list of notifications and its possible  to move to several activities  in the app from this one)

**Comment by abarisain** [comment]
Thank you!

The user should only be able to navigate after the dialog has been dismissed so I don't see how this can crash. I suppose you only saw the crash reports and never experienced it on your end yet?

I don't have any other question so far, I'll get in touch if I do!

**Comment by shaileshmota** [comment]
Okay, noticed another (single) crash. Not sure if related : 
```
Fatal Exception: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.ProgressBar$SavedState
       at android.widget.ProgressBar.onRestoreInstanceState(ProgressBar.java:2414)
       at android.view.View.dispatchRestoreInstanceState(View.java:21578)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4699)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4699)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4699)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4699)
       at android.view.View.restoreHierarchyState(View.java:21556)
       at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:548)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:907)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
       at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
       at com.batch.android.MessagingActivity.onStart(MessagingActivity.java:85)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
       at android.app.Activity.performStart(Activity.java:7978)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3472)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7804)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
```

**Comment by abarisain** [comment]
Thanks, I added it to the ticket so that we look at it at the same time

**Comment by shaileshmota** [comment]
Hello @abarisain any news about these crashes. We have noticed another one popping-up (more frequent) : 
```
Fatal Exception: java.lang.IllegalStateException: Fragment f{b0fa47c (3f674460-1073-4987-bee0-e6e93c577802)} not associated with a fragment manager.
       at androidx.fragment.app.Fragment.requireFragmentManager(Fragment.java:910)
       at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:245)
       at androidx.fragment.app.DialogFragment.dismissAllowingStateLoss(DialogFragment.java:212)
       at com.batch.android.messaging.b.f.dismissAllowingStateLoss(f.java:163)
       at com.batch.android.messaging.b.f.e(f.java:263)
       at com.batch.android.messaging.view.a.b.j(b.java:170)
       at com.batch.android.messaging.view.a.b.lambda$1_ZgRVnH35xdgTkNht69HrYaUbk(b.java)
       at com.batch.android.messaging.view.a.-$$Lambda$b$1_ZgRVnH35xdgTkNht69HrYaUbk.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by abarisain** [comment]
None yet, I didn't manage to reproduce this yet so I'm not even sure what the user sees before this.

Since we can't do anything about a missing fragment manager, we'll probably throw a try catch at it and call it a day.

**Comment by abarisain** [comment]
We'll release a SDK hotfix on may 18/19: we added a check for fragment manager availability

**Comment by abarisain** [comment]
Note: https://github.com/BatchLabs/android-sdk/issues/9#issuecomment-626588877 seems unrelated and we haven't been able to reproduce it

Unfortunately this one is tougher to fix blindly, so I'm not sure it will make it in the hotfix.

**Comment by abarisain** [comment]
Found it: turns out I was trying to reproduce with androidx 1.0.0 and not 1.1.0

With 1.1.0, rotating a fullscreen inapp dismisses it (rather than .. rotating it). If you rotate an in-app with auto dismiss, it eventually crashes when the autodismiss times out and tries to remove the in-app.

About the may 18/19 date: it now depends on how long it takes us to develop a complete fix, and ensure that it works with androidx 1.0, 1.1 and the upcoming 1.2

**Comment by shaileshmota** [comment]
Thank you for the information 🙏

**Comment by abarisain** [comment]
The crash has been fixed: we're now working on fixing rotation. It's turning out to be quite a lot of work, so I'm not sure about a release date, sorry.

**Comment by shaileshmota** [comment]
Thanks for the information. Just to understand the fix will get rid of : https://github.com/BatchLabs/android-sdk/issues/9#issue-615146331 ? 

For us, rotation won't matter as our app doesn't support it (like quite some  apps out  there)
So if we can  scope the release to one crash fix, will be great  😊

**Comment by abarisain** [comment]
We're discussing the scope of the release internally, but we might do just that.

It's a little bit weird that you're getting those crashes if your app does not support rotation. BatchMessagingActivity (which is the support activity  for the fragment) does, but that shouldn't do anything if you disabled rotation for `<application` in the manifest.

Yes, the fix is for the initial issue. Unfortunately we haven't been able to reproduce it: https://github.com/BatchLabs/android-sdk/issues/9#issuecomment-626588877

**Comment by abarisain** [comment]
1.15.2 should fix this.

Fragments are still broken on rotation, this is being worked on for 1.16

Thank you for your help!
